package uk.gov.hmcts.reform.em.stitching.domain.validation;

import jakarta.validation.ConstraintValidator;
import jakarta.validation.ConstraintValidatorContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponentsBuilder;

import java.util.regex.Pattern;

import static java.util.Objects.isNull;

@Component
public class CallableEndpointValidator implements ConstraintValidator<CallableEndpoint, String> {

    private static final Logger log = LoggerFactory.getLogger(CallableEndpointValidator.class);

    private static final String CASE_ID_PATTERN = "\\d{16}";
    private static final String TRIGGER_ID = "asyncStitchingComplete";
    private static final String UUID_PATTERN =
        "[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}";

    private final Pattern compiledPattern;

    public CallableEndpointValidator(
        @Value("${callbackurlvalidator.scheme}") String scheme,
        @Value("${callbackurlvalidator.host}") String host,
        @Value("${callbackurlvalidator.port}") int port) {

        String baseUrl = UriComponentsBuilder.newInstance()
            .scheme(scheme)
            .host(host)
            .port(port)
            .build()
            .toUriString();

        String regexPath = String.format("/api/stitching-complete-callback/%s/%s/%s",
            CASE_ID_PATTERN, TRIGGER_ID, UUID_PATTERN);

        this.compiledPattern = Pattern.compile("^" + Pattern.quote(baseUrl) + regexPath + "$");
    }

    @Override
    public boolean isValid(String urlString, ConstraintValidatorContext context) {
        if (isNull(urlString) || urlString.isBlank()) {
            return false;
        }

        boolean valid = compiledPattern.matcher(urlString).matches();

        if (!valid) {
            log.warn("Callback URL '{}' is invalid or was not generated by the trusted CallbackUrlCreator", urlString);
        }

        return valid;
    }
}