idam_api_base_uri = "https://idam-api.ithc.platform.hmcts.net"
external_hostname = "jcm.ithc.platform.hmcts.net"
external_hostname_www = "www.jcm.ithc.platform.hmcts.net"
external_cert_name = "wildcard-ithc-platform-hmcts-net"
external_cert_vault_uri = "https://infra-vault-qa.vault.azure.net/"
managed_identity_object_id="313c0834-e309-43a8-9298-1320f001e1bd"
dns_server="10.112.11.254"