idam_api_base_uri = "https://idam-api.perftest.platform.hmcts.net"
docmosis_uri = "https://docmosis-testing.platform.hmcts.net/rs/render"
docmosis_templates_uri = "https://docmosis-testing.platform.hmcts.net"
capacity = "2"
managed_identity_object_id="4c8286b6-70db-4baa-8454-e6838b278cab"
dns_server="10.96.139.254"
