idam_api_base_uri = "https://idam-api.platform.hmcts.net"
open_id_api_base_uri = "https://idam-api.platform.hmcts.net/o"
docmosis_uri = "https://docmosis.platform.hmcts.net/rs/convert"
docmosis_render_uri = "https://docmosis.platform.hmcts.net/rs/render"
dns_server="10.96.75.254"
capacity = "2"
