idam_api_base_uri = "https://idam-api.platform.hmcts.net"
open_id_api_base_uri = "https://idam-api.platform.hmcts.net/o"
oidc_issuer_base_uri = "https://forgerock-am.service.core-compute-idam-prod.internal:8443/openam/oauth2/hmcts"
docmosis_uri = "https://docmosis.platform.hmcts.net/rs/convert"
docmosis_render_uri = "https://docmosis.platform.hmcts.net/rs/render"
dns_server="10.96.75.254"
capacity = "2"
managed_identity_object_id="82b164c9-e611-498d-8bd0-d3c01e8df3c8"